&txtLabel=HEADLIGHT (DISCHARGE TYPE) 1/2?LICENSE PLATE LIGHT / PARKING LIGHT / TAILLIGHT?TURN AND HAZARD WARNING LIGHT?AFS (ADAPTIVE FRONT LIGHTING SYSTEM) / HEADLIGHT AUTO LEVELING SYSTEM&
&txtData=S0918_2a?S0918_3?S0918_5?S0918_10&
